import type { Theme } from './types';

export const tokens: Record<keyof Theme, string> = {
  // Colors
  canvasColor: 'var(--canvasColor)',
  textColor: 'var(--textColor)',
  inherit: 'var(--inherit)',
  inheritHover: 'var(--inheritHover)',
  inheritPressed: 'var(--inheritPressed)',
  inheritDisabled: 'var(--inheritDisabled)',
  inheritForegroundHover: 'var(--inheritForegroundHover)',
  inheritForegroundPressed: 'var(--inheritForegroundPressed)',
  inheritBackground: 'var(--inheritBackground)',
  inheritBackgroundDisabled: 'var(--inheritBackgroundDisabled)',
  brand: 'var(--brand)',
  brandHover: 'var(--brandHover)',
  brandPressed: 'var(--brandPressed)',
  brandDisabled: 'var(--brandDisabled)',
  brandForegroundHover: 'var(--brandForegroundHover)',
  brandForegroundPressed: 'var(--brandForegroundPressed)',
  brandBackground: 'var(--brandBackground)',
  brandBackgroundDisabled: 'var(--brandBackgroundDisabled)',
  secondary: 'var(--secondary)',
  secondaryHover: 'var(--secondaryHover)',
  secondaryPressed: 'var(--secondaryPressed)',
  secondaryDisabled: 'var(--secondaryDisabled)',
  secondaryForegroundHover: 'var(--secondaryForegroundHover)',
  secondaryForegroundPressed: 'var(--secondaryForegroundPressed)',
  secondaryBackground: 'var(--secondaryBackground)',
  secondaryBackgroundDisabled: 'var(--secondaryBackgroundDisabled)',
  success: 'var(--success)',
  successHover: 'var(--successHover)',
  successPressed: 'var(--successPressed)',
  successDisabled: 'var(--successDisabled)',
  successForegroundHover: 'var(--successForegroundHover)',
  successForegroundPressed: 'var(--successForegroundPressed)',
  successBackground: 'var(--successBackground)',
  successBackgroundDisabled: 'var(--successBackgroundDisabled)',
  danger: 'var(--danger)',
  dangerHover: 'var(--dangerHover)',
  dangerPressed: 'var(--dangerPressed)',
  dangerDisabled: 'var(--dangerDisabled)',
  dangerForegroundHover: 'var(--dangerForegroundHover)',
  dangerForegroundPressed: 'var(--dangerForegroundPressed)',
  dangerBackground: 'var(--dangerBackground)',
  dangerBackgroundDisabled: 'var(--dangerBackgroundDisabled)',
  social: 'var(--social)',
  socialHover: 'var(--socialHover)',
  socialPressed: 'var(--socialPressed)',
  socialDisabled: 'var(--socialDisabled)',
  socialForegroundHover: 'var(--socialForegroundHover)',
  socialForegroundPressed: 'var(--socialForegroundPressed)',
  socialBackground: 'var(--socialBackground)',
  socialBackgroundDisabled: 'var(--socialBackgroundDisabled)',
  warning: 'var(--warning)',
  warningHover: 'var(--warningHover)',
  warningPressed: 'var(--warningPressed)',
  warningDisabled: 'var(--warningDisabled)',
  warningForegroundHover: 'var(--warningForegroundHover)',
  warningForegroundPressed: 'var(--warningForegroundPressed)',
  warningBackground: 'var(--warningBackground)',
  warningBackgroundDisabled: 'var(--warningBackgroundDisabled)',
  info: 'var(--info)',
  infoHover: 'var(--infoHover)',
  infoPressed: 'var(--infoPressed)',
  infoDisabled: 'var(--infoDisabled)',
  infoForegroundHover: 'var(--infoForegroundHover)',
  infoForegroundPressed: 'var(--infoForegroundPressed)',
  infoBackground: 'var(--infoBackground)',
  infoBackgroundDisabled: 'var(--infoBackgroundDisabled)',

  // Font Family
  baseFont: 'var(--baseFont)',
  monospaceFont: 'var(--monospaceFont)',

  // Font Opacity
  display: 'var(--display)',
  subHeadline: 'var(--subHeadline)',
  body: 'var(--body)',
  caption: 'var(--caption)',
  title: 'var(--title)',
  header1: 'var(--header1)',
  header2: 'var(--header2)',
  header3: 'var(--header3)',

  // Font Weight
  thin: 'var(--thin)',
  light: 'var(--light)',
  regular: 'var(--regular)',
  medium: 'var(--medium)',
  bold: 'var(--bold)',
  black: 'var(--black)',

  // Font Line Height
  lineHeight100: 'var(--lineHeight100)',
  lineHeight200: 'var(--lineHeight200)',
  lineHeight300: 'var(--lineHeight300)',
  lineHeight400: 'var(--lineHeight400)',
  lineHeight500: 'var(--lineHeight500)',
  lineHeight600: 'var(--lineHeight600)',
  lineHeight700: 'var(--lineHeight700)',
  lineHeight800: 'var(--lineHeight800)',
  lineHeight900: 'var(--lineHeight900)',
  lineHeight1000: 'var(--lineHeight1000)',

  // Font Size
  fontSize100: 'var(--fontSize100)',
  fontSize200: 'var(--fontSize200)',
  fontSize300: 'var(--fontSize300)',
  fontSize400: 'var(--fontSize400)',
  fontSize500: 'var(--fontSize500)',
  fontSize600: 'var(--fontSize600)',
  fontSize700: 'var(--fontSize700)',
  fontSize800: 'var(--fontSize800)',
  fontSize900: 'var(--fontSize900)',
  fontSize1000: 'var(--fontSize1000)',
};
